source 'http://rubygems.org'
ruby '2.2.3'

gem 'activerecord'
gem 'sinatra-activerecord'
#gem 'sqlite3'
gem 'rake'
gem 'sinatra-flash'

 group :development do        
  gem 'sqlite3'
  end

   group :production do         
   	gem 'pg'   
   end